# Generated by Django 5.1.6 on 2025-02-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='Name',
            new_name='name',
        ),
    ]
